name: income_life
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_state_notifier: ^0.7.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  gsheets: ^0.4.2
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  simple_logger: ^1.9.0+1
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true

import_path_converter:
  relative: true
